// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2zKZUqWW34eKV6zF30ltM5qQ0n37ZAqg',
    appId: '1:176962835843:web:b7c493357931372d8992b6',
    messagingSenderId: '176962835843',
    projectId: 'oas-app2',
    authDomain: 'oas-app2.firebaseapp.com',
    storageBucket: 'oas-app2.appspot.com',
    measurementId: 'G-D97CPKT051',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfeNTrHnGbfRp85B-5QS50jDEaW6g2Y9o',
    appId: '1:176962835843:android:ce7e4766ffbfbd3b8992b6',
    messagingSenderId: '176962835843',
    projectId: 'oas-app2',
    storageBucket: 'oas-app2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGBqT1T6o5twqihChYXjvSKDNl3L1xfdM',
    appId: '1:176962835843:ios:84e58eabacca1efa8992b6',
    messagingSenderId: '176962835843',
    projectId: 'oas-app2',
    storageBucket: 'oas-app2.appspot.com',
    iosBundleId: 'com.example.oas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2zKZUqWW34eKV6zF30ltM5qQ0n37ZAqg',
    appId: '1:176962835843:web:54b4db0576cc8d768992b6',
    messagingSenderId: '176962835843',
    projectId: 'oas-app2',
    authDomain: 'oas-app2.firebaseapp.com',
    storageBucket: 'oas-app2.appspot.com',
    measurementId: 'G-Y97589S17L',
  );
}
